name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: beeat-front-api

jobs:
  # test:
  #   name: Run Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'yarn'

  #     - name: Install dependencies
  #       run: yarn install --frozen-lockfile

      # - name: Lint code
      #   run: npx nx lint @beeat-be/apis

      # - name: Type check
      #   run: npx nx typecheck @beeat-be/apis

      # - name: Run unit tests (if any)
      #   run: npx nx test @beeat-be/apis --passWithNoTests

  build-and-deploy:
    name: Build Application and Deploy Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    outputs:
      image-digest: ${{ steps.build-docker.outputs.digest }}
      image-uri: ${{ steps.build-docker.outputs.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma client
        run: npx prisma generate --schema=packages/prisma/scheams/schema.prisma

      - name: Build application
        run: npx nx build @beeat-be/apis --prod

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./apps/apis/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quangdh/beeat-front-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
          # Enable BuildKit for better caching
          builder: ${{ steps.buildx.outputs.name }}
          provenance: false
          sbom: false
